name: motion

display_name: Motion

version: 1.0.0

author:
  name: "Mutlipurpose theme"
  email: "kelkoul@gmail.com"
  url: ""

meta:
  compatibility:
    from: 9.1.2
    to: ~9.1.2
    framework: bootstrap-v5.3.3

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

global_settings:
  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    category_default:
      width: 180
      height: 180
      scope: [categories]
    stores_default:
      width: 287
      height: 160
      scope: [stores]
    default_xs:
      width: 160
      height: 160
      scope: [products, manufacturers, suppliers, categories]
    default_sm:
      width: 216
      height: 216
      scope: [categories, products]
    default_md:
      width: 261
      height: 261
      scope: [manufacturers, suppliers, products, categories]
    default_lg:
      width: 336
      height: 336
      scope: [categories, products]
    default_xl:
      width: 400
      height: 400
      scope: [products]
    product_main:
      width: 720
      height: 720
      scope: [products]
    category_cover:
      width: 1000
      height: 200
      scope: [categories]
    product_main_2x:
      width: 1440
      height: 1440
      scope: [products]
    category_cover_2x:
      width: 2000
      height: 400
      scope: [categories]
      
theme_settings:
  rtl_generation: false
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    contact: layout-left-column
    manufacturer: layout-left-column
    supplier: layout-left-column
